"""LangGraph state machine wiring (M3).

Composition only — every classification/retrieval/generation decision lives in
``router.py``, ``nodes.py``, and the M2 ``QueryEngine``. This file just declares
the topology so the run is visualisable and the routing is explicit.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from langgraph.graph import END, START, StateGraph

from research_navigator.agents.nodes import (
    NodeDeps,
    compare_approaches_node,
    concept_explanation_node,
    fallback_node,
    find_papers_node,
    paper_deep_dive_node,
    recent_developments_node,
)
from research_navigator.agents.router import classify_query
from research_navigator.agents.state import AgentRoute, AgentState
from research_navigator.config import Settings, get_settings
from research_navigator.generate.pipeline import QueryEngine
from research_navigator.ingest.manifest import load_manifest
from research_navigator.logging import get_logger

log = get_logger(__name__)


def build_agent_graph(
    settings: Settings | None = None,
    *,
    engine: QueryEngine | None = None,
) -> Any:
    """Build and compile the LangGraph state machine.

    Args:
        settings: Project settings; defaults to :func:`get_settings`.
        engine: A pre-built :class:`QueryEngine` (lets tests inject mocks).
    """
    settings = settings or get_settings()
    engine = engine or QueryEngine(settings)
    manifest = load_manifest(settings.manifest_path)
    deps = NodeDeps(settings=settings, engine=engine, documents=list(manifest.documents))

    graph = StateGraph(AgentState)

    # Router: classifies the query and emits hints. No side effects.
    def router_node(state: AgentState) -> dict[str, Any]:
        route, hints = classify_query(state.query, deps.documents)
        log.info(
            "router_decision",
            query=state.query,
            route=route.value,
            hints=hints.model_dump(),
        )
        return {"route": route, "hints": hints}

    # Sub-capability nodes (closures over deps).
    def _concept(state: AgentState) -> dict[str, Any]:
        return concept_explanation_node(state, deps)

    def _paper_deep_dive(state: AgentState) -> dict[str, Any]:
        return paper_deep_dive_node(state, deps)

    def _compare(state: AgentState) -> dict[str, Any]:
        return compare_approaches_node(state, deps)

    def _recent(state: AgentState) -> dict[str, Any]:
        return recent_developments_node(state, deps)

    def _find_papers(state: AgentState) -> dict[str, Any]:
        return find_papers_node(state, deps)

    def _fallback(state: AgentState) -> dict[str, Any]:
        return fallback_node(state, deps)

    graph.add_node("router", router_node)
    graph.add_node(AgentRoute.CONCEPT_EXPLANATION.value, _concept)
    graph.add_node(AgentRoute.PAPER_DEEP_DIVE.value, _paper_deep_dive)
    graph.add_node(AgentRoute.COMPARE_APPROACHES.value, _compare)
    graph.add_node(AgentRoute.RECENT_DEVELOPMENTS.value, _recent)
    graph.add_node(AgentRoute.FIND_PAPERS.value, _find_papers)
    graph.add_node(AgentRoute.OUT_OF_SCOPE.value, _fallback)

    # Wiring.
    graph.add_edge(START, "router")

    def route_selector(state: AgentState) -> str:
        return (state.route or AgentRoute.CONCEPT_EXPLANATION).value

    graph.add_conditional_edges(
        "router",
        route_selector,
        {r.value: r.value for r in AgentRoute},
    )
    for r in AgentRoute:
        graph.add_edge(r.value, END)

    return graph.compile()


def render_graph_mermaid(compiled: Any | None = None) -> str:
    """Return a Mermaid diagram of the agent graph."""
    if compiled is None:
        compiled = build_agent_graph()
    return str(compiled.get_graph().draw_mermaid())


def save_graph_visualization(out_path: Path, compiled: Any | None = None) -> Path:
    """Write the Mermaid diagram to ``out_path`` (GitHub renders mermaid natively)."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    mermaid = render_graph_mermaid(compiled)
    body = (
        "# AI Research Navigator — Agent Graph\n\n"
        "Auto-generated by `research_navigator.agents.graph.save_graph_visualization`.\n\n"
        f"```mermaid\n{mermaid}\n```\n"
    )
    out_path.write_text(body, encoding="utf-8")
    return out_path
